# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-14 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='memo',
            field=models.CharField(default='', max_length=32),
        ),
    ]
