# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-23 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassStudtyRecord',
            new_name='ClassStudyRecord',
        ),
        migrations.RenameField(
            model_name='studentstudyrecord',
            old_name='class_studty_record',
            new_name='class_study_record',
        ),
    ]
